services:
  we_are_kadence.tls_aware_redis_dsn_env_var_processor:
    class: Kadence\TlsAwareRedisDsnProcessor\TlsAwareRedisSchemeEnvVarProcessor
    tags:
      - { name: container.env_var_processor }